version: '3.8'
services:
  chat-room-ui:
    image: chat-room-ui:latest
    ports:
      - 80:80
    depends_on:
      - chat-room-backend
    networks:
      - common-network
  chat-room-backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3007:3007
    networks:
      - common-network
    env_file:
      - .env
  mysql-container:
    image: mysql
    volumes:
      - /Users/shiyanchen/Applications/mysql-docker-mounted-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: chat_room
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/shiyanchen/Applications/redis-docker-mounted-data:/data
    ports:
      - 6379:6379
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
